/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication11;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Essra
 */
public class edit_spot extends javax.swing.JFrame {

    /**
     * Creates new form edit_spot
     */
        DefaultTableModel tbl = new DefaultTableModel();

    public edit_spot() {
        
        initComponents();
     
//        
//          tbl.addColumn("spot name");
//          tbl.addColumn("spot status");
//          .setModel(tbl);
//        
//            try {
//            db DB = new db();
//            SQLException ex = new SQLException();
//            ResultSet res = DB.veiwSpots();
//
//            while (res.next()) {
//                tbl.addRow(new String[]{
//                    res.getString(1),
//                    res.getString(2),});
//            }
//               DB.CloseConnection();
//
//        } catch (SQLException ex) {
//              JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
//          
//    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        editing_spot = new javax.swing.JLabel();
        add_spots = new javax.swing.JButton();
        delete_spots = new javax.swing.JButton();
        view = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtstatue = new javax.swing.JTextField();
        pay = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editing_spot.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editing_spot.setText("spots");

        add_spots.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add_spots.setText("add spots");
        add_spots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_spotsActionPerformed(evt);
            }
        });

        delete_spots.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        delete_spots.setText("delete spots");
        delete_spots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_spotsActionPerformed(evt);
            }
        });

        view.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        view.setText("view report");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        jLabel1.setText("spot number");

        jLabel2.setText("spot status");

        txtstatue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstatueActionPerformed(evt);
            }
        });

        pay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pay.setText("total payment");
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });

        edit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edit.setText("edit spot status");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("log out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(add_spots)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edit)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(editing_spot)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtname, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(txtstatue))
                        .addGap(76, 76, 76))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(delete_spots)
                        .addContainerGap(25, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(pay)
                        .addGap(75, 75, 75)
                        .addComponent(view))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtstatue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(editing_spot)))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_spots)
                    .addComponent(delete_spots)
                    .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(view))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void delete_spotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_spotsActionPerformed
        // TODO add your handling code here:
        try {
              db DB=new db();
              SQLException ex = new SQLException();

              int i;
             i = Integer.parseInt(txtname.getText());
              
              DB.removeSpot(i);
               JOptionPane.showMessageDialog(null, "removed Successfully","", JOptionPane.INFORMATION_MESSAGE);
               DB.CloseConnection();
            } catch (SQLException ex) {
                Logger.getLogger(edit_spot.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_delete_spotsActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
        updated_admin_eport r=new updated_admin_eport();
        r.setLocation(200, 200);
        r.setVisible(true);
        this.dispose(); 
        
    }//GEN-LAST:event_viewActionPerformed

    private void add_spotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_spotsActionPerformed
        // TODO add your handling code here:
        try {
              db DB=new db();
              SQLException ex = new SQLException();

              int i;
             i = Integer.parseInt(txtname.getText());
              String statue=txtstatue.getText();
              DB.setSpot(i, statue);
               JOptionPane.showMessageDialog(null, "Added Successfully","", JOptionPane.INFORMATION_MESSAGE);
               DB.CloseConnection();
            } catch (SQLException ex) {
                Logger.getLogger(edit_spot.class.getName()).log(Level.SEVERE, null, ex);
            }

//        updated_admin_eport r=new updated_admin_eport();
//        r.setLocation(200, 200);
//        r.setVisible(true);
//        this.dispose();  
    }//GEN-LAST:event_add_spotsActionPerformed

    private void txtstatueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstatueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstatueActionPerformed

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        // TODO add your handling code here:
          payment r=new payment();
        r.setLocation(200, 200);
        r.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_payActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
          try {
              db DB=new db();
              SQLException ex = new SQLException();

              int i;
              i = Integer.parseInt(txtname.getText());
              String statue=txtstatue.getText();
              DB.editSpot(i, statue);
               JOptionPane.showMessageDialog(null, "Successfully edited","", JOptionPane.INFORMATION_MESSAGE);
               DB.CloseConnection();
            } catch (SQLException ex) {
                Logger.getLogger(edit_spot.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_editActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        users r=new users();
        r.setLocation(200, 200);
        r.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_spot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_spot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_spot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_spot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_spot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_spots;
    private javax.swing.JButton delete_spots;
    private javax.swing.JButton edit;
    private javax.swing.JLabel editing_spot;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton pay;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtstatue;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
